// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txmudblxqhbcpswqxzuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bXVkYmx4cWhiY3Bzd3F4enVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTUyMzksImV4cCI6MjA2NjAzMTIzOX0.YOz2STqhwbNYABhjEm-ZNw16lApT6GQy3KsaUMcYh7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);